/// Flutter icons AppIconData
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIconData
///      fonts:
///       - asset: fonts/AppIconData.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppIconData {
  AppIconData._();

  static const _kFontFam = 'AppIconData';
  static const String? _kFontPkg = null;

  static const IconData first = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData last = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart_icon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData earth_icon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_icon = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
